# Generated by Django 5.0.2 on 2024-02-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TBTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('Phone_number', models.IntegerField()),
                ('Email', models.CharField(max_length=50, verbose_name='Email')),
                ('day_of_barth', models.IntegerField(verbose_name='Год раждение')),
            ],
            options={
                'verbose_name': 'Гурӯҳ',
                'verbose_name_plural': 'Гурӯҳҳо',
            },
        ),
    ]
