# Generated by Django 5.0.2 on 2024-02-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TBTI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbti',
            name='day_of_barth',
            field=models.DateField(verbose_name='Год раждение'),
        ),
    ]
